services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    volumes:
      - ./backend/mediamtx.yml:/mediamtx.yml:ro

    restart: unless-stopped
  backend:
    build: ./backend
    container_name: stream_backend
    ports:
      - "3000:3000"
    depends_on:
      - mediamtx
    environment:
      - NODE_ENV=production
      - MEDIA_SERVER=http://mediamtx:8888
      - PORT=3000
    restart: unless-stopped
